base:
# stuff pertaining to everything
  random_state: 42
  log_level: INFO

data_load:
# data ins and outs
  dataset_csv: 'data/raw/AirQualityUCI.csv'
  dataset_csv_cleaned: 'data/raw/AirQualityUCI_cleaned.csv'

featurize:
  X_scaled_csv_path: 'data/processed/csv_X_scaled_featurized.csv'
  y_csv_path: 'data/processed/csv_y_featurized.csv'
  cols_to_drop: ['Date','Time','NMHC(GT)','C6H6(GT)','PT08.S1(CO)','PT08.S2(NMHC)','PT08.S3(NOx)']


data_split:
  test_size: 0.2
  X_train_csv_path: 'data/splitdata/X_train.csv'
  X_test_csv_path: 'data/splitdata/X_test.csv'
  X_train_scaled_csv_path: 'data/splitdata/X_train_scaled.csv'
  X_test_scaled_csv_path: 'data/splitdata/X_test_scaled.csv'
  y_train_csv_path: 'data/splitdata/y_train.csv'
  y_test_csv_path: 'data/splitdata/y_test.csv'

train:
# training related items
  cv: 3
  estimator_name: rdm_forest
  estimators:
    rdm_forest:
      param_grid: # params of GridSearchCV constructor
        n_estimators: [10, 20, 50]
        max_features: ['sqrt']
        max_depth: [5, 10]
        min_samples_split: [2, 5]
        min_samples_leaf: [1, 2]
  model_path: models/model.joblib


evaluate:
# metrics, reports, jsons, etc. the outputs
  reports_dir: reports
  metrics_file: 'metrics.json'
  #confusion_matrix_image: 'reports/confusion_matrix.png'